# Generated by Django 6.0.5 on 2026-08-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'WORKER'), ('customer', 'CUSTOMER'), ('admin', 'ADMIN')], db_index=True, default='customer', max_length=15),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
